import Head from 'next/head';
import Navbar from '../components/navbar/navbar';
import Overview from '../components/overview/overview';
import Sidebar from '../components/sidebar/sidebar';

export default function Home() {
  return (
    <div className="main-bg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="row">
          <div className="col-md-3">
            <Sidebar />
          </div>
          <div className="col-md-9">
            <Navbar />
            <Overview />
          </div>
        </div>
      </div>
    </div>
  );
}
