import Head from 'next/head';
import Analytics from '../components/analytics/analytics';
import Navbar from '../components/navbar/navbar';
import Nfc from '../components/nfc/nfc';
import Overview from '../components/overview/overview';
import Projects from '../components/projects/projects';
import QrCodeTemplate from '../components/qrCodeTemplate/qrCodeTemplate';
import QrCodes from '../components/quCodes/quCodes';
import Sidebar from '../components/sidebar/sidebar';

export default function Home() {
  return (
    <div className="main-bg overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container vh-100">
        <div className="row">
          <div className="col-md-3">
            <Sidebar />
          </div>
          <div className="col-md-9 ">
            <Navbar />
            {/* <Overview /> */}
            {/* <Projects /> */}
            <QrCodeTemplate />
            {/* <Nfc /> */}
            {/* <Analytics /> */}
            {/* <QrCodes /> */}
          </div>
        </div>
      </div>
    </div>
  );
}
